# PyTorch Tutorial 03: Define Networks
## Overview
In this tutorial, we explain how to define networks. 

In [1]:
import torch
import torch.nn as nn

In [3]:
x = torch.rand([8, 100, 10]).detach()
x

tensor([[[0.9810, 0.7243, 0.2028,  ..., 0.5094, 0.5279, 0.4592],
         [0.4878, 0.3412, 0.3422,  ..., 0.0102, 0.9720, 0.5414],
         [0.1226, 0.8022, 0.7981,  ..., 0.1571, 0.0988, 0.6781],
         ...,
         [0.4581, 0.9685, 0.6707,  ..., 0.5093, 0.5106, 0.5539],
         [0.1790, 0.2048, 0.3654,  ..., 0.6950, 0.0654, 0.4310],
         [0.0511, 0.6755, 0.0117,  ..., 0.7128, 0.2348, 0.6461]],

        [[0.2471, 0.8003, 0.3972,  ..., 0.4543, 0.5456, 0.4218],
         [0.2414, 0.2463, 0.6018,  ..., 0.8780, 0.6957, 0.4956],
         [0.1226, 0.6209, 0.2575,  ..., 0.2627, 0.5403, 0.0066],
         ...,
         [0.0560, 0.2617, 0.8878,  ..., 0.7122, 0.0779, 0.1661],
         [0.9867, 0.7888, 0.7805,  ..., 0.2494, 0.9250, 0.3705],
         [0.9823, 0.4269, 0.5620,  ..., 0.1381, 0.2027, 0.6251]],

        [[0.0234, 0.3615, 0.8709,  ..., 0.7043, 0.1336, 0.5895],
         [0.8184, 0.8761, 0.3484,  ..., 0.7436, 0.2964, 0.4625],
         [0.4372, 0.3978, 0.6816,  ..., 0.2054, 0.3076, 0.

In [4]:
x.shape

torch.Size([8, 100, 10])

In [6]:
y = torch.rand(8)
y = (y > 0.5).int()
y

tensor([0, 1, 1, 1, 0, 1, 0, 1], dtype=torch.int32)

In [7]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.first_layer = nn.Linear(1000, 50)
        self.second_layer = nn.Linear(50, 1)
    def forward(self, x):
        x = torch.flatten(x, start_dim=1, end_dim=2)
        x = nn.functional.relu(self.first_layer(x))
        x = self.second_layer(x)
        return x

In [8]:
mlp = MLP()
output = mlp(x)

In [9]:
output

tensor([[-0.0774],
        [-0.0861],
        [-0.2170],
        [-0.0578],
        [-0.0194],
        [-0.0544],
        [-0.0185],
        [-0.0751]], grad_fn=<AddmmBackward>)

In [12]:
class Embedding(nn.Module):
    def __init__(self):
        super(Embedding, self).__init__()
        self.embedding = nn.Embedding(4, 100)
    def forward(self, x):
        return self.embedding(x)

In [13]:
embedding = Embedding()
embedding_input = torch.tensor([[0, 1, 0], [2, 3, 3]])
embedding_output = embedding(embedding_input)

In [15]:
embedding_output.shape

torch.Size([2, 3, 100])

In [16]:
embedding_output

tensor([[[ 0.1649, -1.0764, -0.1969,  1.8058, -1.8152,  0.7977, -1.7878,
           0.2581, -2.5786,  1.0233, -0.5009,  1.8050, -0.6063, -1.6171,
          -1.1114,  1.0527, -0.3070, -1.6617, -2.6620,  0.5013,  0.2302,
           0.0481,  3.4440,  1.1627,  0.8570, -0.3099,  1.0893,  0.2568,
           1.7849,  1.0496,  1.1088,  0.6544,  0.9007, -2.3732, -1.7758,
           1.8441,  0.7471, -1.9639,  0.9035,  0.2455, -1.5268, -0.3086,
           0.2642, -0.7480, -0.3609,  1.7102,  1.4613,  0.0153, -0.1549,
          -0.9048,  1.4272,  0.3370,  0.9153, -0.0760,  0.7364,  1.1759,
           0.8261,  0.7357,  0.1300,  2.0840, -1.0127, -0.3228, -1.6187,
          -0.0731, -0.7419, -0.1789,  0.6655, -0.7230,  0.5533,  1.4748,
          -1.7801, -2.7300,  1.1389,  0.4410,  0.7421,  0.0083,  0.5886,
          -0.7179,  0.6583, -1.1857,  0.5183, -1.2644, -0.9329, -0.5142,
           0.5695, -0.7105, -0.4348, -0.5379,  0.2753,  1.7908, -0.1770,
          -0.1244, -0.7275,  1.8007, -0.3717,  0.26

In [17]:
class LSTM(nn.Module):
    def __init__(self):
        super(LSTM, self).__init__()
        self.lstm = nn.LSTM(10,
                            15,
                            num_layers=2,
                            bidirectional=True,
                            dropout=0.1)
    def forward(self, x):
        output, (hidden, cell) = self.lstm(x)
        return output, hidden, cell

In [20]:
permute_x = x.permute([1, 0, 2])
permute_x.shape

torch.Size([100, 8, 10])

In [21]:
lstm = LSTM()
output_lstm1, output_lstm2, output_lstm3 = lstm(permute_x)

In [22]:
output_lstm1.shape

torch.Size([100, 8, 30])

In [23]:
output_lstm2.shape

torch.Size([4, 8, 15])

In [24]:
output_lstm3.shape

torch.Size([4, 8, 15])

In [25]:
class Conv(nn.Module):
    def __init__(self):
        super(Conv, self).__init__()
        self.conv1d = nn.Conv1d(100, 50, 2)
    def forward(self, x):
        return self.conv1d(x)

In [26]:
conv = Conv()
output = conv(x)

In [27]:
output.shape

torch.Size([8, 50, 9])